export type FieldType =
  | "text"
  | "textarea"
  | "number"
  | "money"
  | "date"
  | "datetime"
  | "select"
  | "boolean"
  | "tags"
  | "relation";

export type FieldDef = {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { value: string; label: string }[];
  relationTable?: string;
  relationLabelKey?: string;
  placeholder?: string;
  default?: unknown;
  hint?: string;
};

export type ResourceDef = {
  table: string;
  key: string;
  label: string;
  labelPlural: string;
  fields: FieldDef[];
  titleKey: string;
  subtitleKeys?: string[];
  orderBy?: { column: string; ascending?: boolean };
  softDeleteColumn?: "archived_at";
  searchKeys?: string[];
};

const notes: FieldDef = { key: "notes", label: "Notes", type: "textarea" };
const status = (options: string[], def?: string): FieldDef => ({
  key: "status",
  label: "Status",
  type: "select",
  options: options.map((o) => ({ value: o, label: o })),
  default: def ?? options[0],
});
const priority3: FieldDef = {
  key: "priority",
  label: "Priority",
  type: "select",
  options: [
    { value: "1", label: "1 — Critical" },
    { value: "2", label: "2 — High" },
    { value: "3", label: "3 — Normal" },
  ],
  default: "2",
};
const currency: FieldDef = { key: "currency", label: "Currency", type: "text", default: "THB" };

export const RESOURCES: Record<string, ResourceDef> = {
  businesses: {
    table: "businesses",
    key: "businesses",
    label: "Business",
    labelPlural: "Businesses",
    titleKey: "name",
    subtitleKeys: ["type", "status"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    searchKeys: ["name", "description"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "type", label: "Type", type: "text" },
      status(["idea", "building", "active", "paused", "closed"], "building"),
      { key: "focus", label: "Focus", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      notes,
    ],
  },
  projects: {
    table: "projects",
    key: "projects",
    label: "Project",
    labelPlural: "Projects",
    titleKey: "name",
    subtitleKeys: ["category", "status"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    searchKeys: ["name", "description", "next_action"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "business_id", label: "Business", type: "relation", relationTable: "businesses", relationLabelKey: "name" },
      { key: "goal_id", label: "Goal", type: "relation", relationTable: "goals", relationLabelKey: "title" },
      { key: "category", label: "Category", type: "text" },
      status(["planned", "active", "building", "blocked", "done"], "active"),
      priority3,
      { key: "start_date", label: "Start date", type: "date" },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "budget", label: "Budget", type: "money" },
      {
        key: "progress_mode",
        label: "Progress mode",
        type: "select",
        options: [
          { value: "explicit", label: "Explicit %" },
          { value: "computed", label: "Computed from milestones" },
        ],
        default: "explicit",
      },
      { key: "explicit_progress", label: "Progress %", type: "number" },
      { key: "next_milestone", label: "Next milestone", type: "text" },
      { key: "next_action", label: "Next action", type: "text" },
      { key: "blocker", label: "Blocker", type: "textarea" },
      { key: "description", label: "Description", type: "textarea" },
      notes,
    ],
  },
  goals: {
    table: "goals",
    key: "goals",
    label: "Goal",
    labelPlural: "Goals",
    titleKey: "title",
    subtitleKeys: ["level", "status"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    searchKeys: ["title", "description"],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      {
        key: "level",
        label: "Level",
        type: "select",
        options: ["north_star", "yearly", "quarterly", "monthly"].map((v) => ({ value: v, label: v })),
        default: "quarterly",
      },
      { key: "parent_goal_id", label: "Parent goal", type: "relation", relationTable: "goals", relationLabelKey: "title" },
      { key: "domain", label: "Domain", type: "text" },
      status(["active", "paused", "achieved", "dropped"], "active"),
      { key: "target_value", label: "Target value", type: "number" },
      { key: "current_value", label: "Current value", type: "number" },
      { key: "unit", label: "Unit", type: "text" },
      { key: "tracking_method", label: "Tracking method", type: "text" },
      { key: "deadline", label: "Deadline", type: "date" },
      priority3,
      { key: "description", label: "Description", type: "textarea" },
      notes,
    ],
  },
  milestones: {
    table: "milestones",
    key: "milestones",
    label: "Milestone",
    labelPlural: "Milestones",
    titleKey: "title",
    subtitleKeys: ["status"],
    orderBy: { column: "position", ascending: true },
    fields: [
      { key: "project_id", label: "Project", type: "relation", relationTable: "projects", relationLabelKey: "name", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      status(["pending", "done"], "pending"),
      { key: "due_date", label: "Due date", type: "date" },
      { key: "position", label: "Position", type: "number", default: 0 },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  tasks: {
    table: "tasks",
    key: "tasks",
    label: "Task",
    labelPlural: "Tasks",
    titleKey: "title",
    subtitleKeys: ["status", "priority"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    searchKeys: ["title", "description"],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      status(["todo", "doing", "done"], "todo"),
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "med", label: "Medium" },
          { value: "high", label: "High" },
        ],
        default: "med",
      },
      { key: "project_id", label: "Project", type: "relation", relationTable: "projects", relationLabelKey: "name" },
      { key: "business_id", label: "Business", type: "relation", relationTable: "businesses", relationLabelKey: "name" },
      { key: "goal_id", label: "Goal", type: "relation", relationTable: "goals", relationLabelKey: "title" },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "due_time", label: "Due time", type: "text", placeholder: "HH:MM" },
      { key: "is_today_priority", label: "Top 3 today", type: "boolean" },
      { key: "tags", label: "Tags", type: "tags" },
      { key: "description", label: "Description", type: "textarea" },
      notes,
    ],
  },
  schedule_events: {
    table: "schedule_events",
    key: "schedule_events",
    label: "Event",
    labelPlural: "Schedule",
    titleKey: "title",
    subtitleKeys: ["category", "status"],
    orderBy: { column: "start_time", ascending: true },
    softDeleteColumn: "archived_at",
    searchKeys: ["title", "location"],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "start_time", label: "Start", type: "datetime", required: true },
      { key: "end_time", label: "End", type: "datetime" },
      { key: "all_day", label: "All day", type: "boolean" },
      { key: "category", label: "Category", type: "text" },
      status(["scheduled", "done", "cancelled"], "scheduled"),
      priority3,
      { key: "location", label: "Location", type: "text" },
      { key: "business_id", label: "Business", type: "relation", relationTable: "businesses", relationLabelKey: "name" },
      { key: "project_id", label: "Project", type: "relation", relationTable: "projects", relationLabelKey: "name" },
      notes,
    ],
  },
  financial_accounts: {
    table: "financial_accounts",
    key: "financial_accounts",
    label: "Account",
    labelPlural: "Accounts",
    titleKey: "name",
    subtitleKeys: ["account_type", "institution"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      {
        key: "account_type",
        label: "Type",
        type: "select",
        options: ["cash", "bank", "credit", "wallet", "other"].map((v) => ({ value: v, label: v })),
        default: "bank",
      },
      { key: "institution", label: "Institution", type: "text" },
      currency,
      { key: "opening_balance", label: "Opening balance", type: "money", default: 0 },
      { key: "is_active", label: "Active", type: "boolean", default: true },
      notes,
    ],
  },
  transaction_categories: {
    table: "transaction_categories",
    key: "transaction_categories",
    label: "Category",
    labelPlural: "Categories",
    titleKey: "name",
    subtitleKeys: ["transaction_type"],
    orderBy: { column: "position", ascending: true },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      {
        key: "transaction_type",
        label: "Type",
        type: "select",
        options: [
          { value: "income", label: "Income" },
          { value: "expense", label: "Expense" },
        ],
        default: "expense",
      },
      { key: "color", label: "Color", type: "text", placeholder: "#e1ba70" },
      { key: "icon", label: "Icon", type: "text" },
      { key: "position", label: "Position", type: "number", default: 0 },
    ],
  },
  transactions: {
    table: "transactions",
    key: "transactions",
    label: "Transaction",
    labelPlural: "Transactions",
    titleKey: "description",
    subtitleKeys: ["type", "category"],
    orderBy: { column: "occurred_at", ascending: false },
    softDeleteColumn: "archived_at",
    searchKeys: ["description", "merchant"],
    fields: [
      {
        key: "type",
        label: "Type",
        type: "select",
        required: true,
        options: [
          { value: "income", label: "Income" },
          { value: "expense", label: "Expense" },
          { value: "transfer", label: "Transfer" },
        ],
        default: "expense",
      },
      { key: "amount", label: "Amount", type: "money", required: true },
      currency,
      { key: "occurred_at", label: "Date", type: "date", required: true },
      { key: "account_id", label: "Account", type: "relation", relationTable: "financial_accounts", relationLabelKey: "name" },
      { key: "transfer_account_id", label: "Transfer to account", type: "relation", relationTable: "financial_accounts", relationLabelKey: "name" },
      { key: "category_id", label: "Category", type: "relation", relationTable: "transaction_categories", relationLabelKey: "name" },
      { key: "merchant", label: "Merchant", type: "text" },
      { key: "business_id", label: "Business", type: "relation", relationTable: "businesses", relationLabelKey: "name" },
      { key: "project_id", label: "Project", type: "relation", relationTable: "projects", relationLabelKey: "name" },
      { key: "description", label: "Description", type: "text" },
      notes,
    ],
  },
  budgets: {
    table: "budgets",
    key: "budgets",
    label: "Budget",
    labelPlural: "Budgets",
    titleKey: "category",
    subtitleKeys: ["period_month"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "category", label: "Category", type: "text", required: true },
      { key: "monthly_limit", label: "Monthly limit", type: "money", required: true },
      currency,
      { key: "period_month", label: "Month", type: "date" },
      notes,
    ],
  },
  assets: {
    table: "assets",
    key: "assets",
    label: "Asset",
    labelPlural: "Assets",
    titleKey: "name",
    subtitleKeys: ["type"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "type", label: "Type", type: "text" },
      { key: "value", label: "Value", type: "money", required: true },
      currency,
      { key: "valuation_date", label: "Valuation date", type: "date" },
      notes,
    ],
  },
  debts: {
    table: "debts",
    key: "debts",
    label: "Debt",
    labelPlural: "Debts",
    titleKey: "name",
    subtitleKeys: ["type"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "type", label: "Type", type: "text" },
      { key: "balance", label: "Balance", type: "money", required: true },
      currency,
      { key: "interest_rate", label: "Interest rate %", type: "number" },
      { key: "minimum_payment", label: "Minimum payment", type: "money" },
      { key: "due_day", label: "Due day of month", type: "number" },
      { key: "lender", label: "Lender", type: "text" },
      notes,
    ],
  },
  recurring_transactions: {
    table: "recurring_transactions",
    key: "recurring_transactions",
    label: "Recurring",
    labelPlural: "Recurring Expenses",
    titleKey: "title",
    subtitleKeys: ["frequency", "type"],
    orderBy: { column: "next_occurrence", ascending: true },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      {
        key: "type",
        label: "Type",
        type: "select",
        options: [
          { value: "income", label: "Income" },
          { value: "expense", label: "Expense" },
        ],
        default: "expense",
      },
      { key: "amount", label: "Amount", type: "money", required: true },
      currency,
      {
        key: "frequency",
        label: "Frequency",
        type: "select",
        options: ["daily", "weekly", "monthly", "yearly"].map((v) => ({ value: v, label: v })),
        default: "monthly",
      },
      { key: "next_occurrence", label: "Next occurrence", type: "date", required: true },
      { key: "account_id", label: "Account", type: "relation", relationTable: "financial_accounts", relationLabelKey: "name" },
      { key: "category_id", label: "Category", type: "relation", relationTable: "transaction_categories", relationLabelKey: "name" },
      { key: "is_active", label: "Active", type: "boolean", default: true },
      notes,
    ],
  },
  holdings: {
    table: "holdings",
    key: "holdings",
    label: "Holding",
    labelPlural: "Holdings",
    titleKey: "ticker",
    subtitleKeys: ["market", "asset_class"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "ticker", label: "Ticker", type: "text", required: true },
      { key: "name", label: "Name", type: "text" },
      { key: "market", label: "Market", type: "text", placeholder: "SET / NASDAQ / NYSE" },
      { key: "quantity", label: "Quantity", type: "number", required: true },
      { key: "avg_cost", label: "Average cost", type: "money" },
      currency,
      { key: "asset_class", label: "Asset class", type: "text" },
      { key: "broker", label: "Broker", type: "text" },
      notes,
    ],
  },
  watchlists: {
    table: "watchlists",
    key: "watchlists",
    label: "Watchlist",
    labelPlural: "Watchlists",
    titleKey: "name",
    orderBy: { column: "position", ascending: true },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "position", label: "Position", type: "number", default: 0 },
    ],
  },
  watchlist_items: {
    table: "watchlist_items",
    key: "watchlist_items",
    label: "Watch item",
    labelPlural: "Watchlist",
    titleKey: "ticker",
    subtitleKeys: ["market"],
    orderBy: { column: "position", ascending: true },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "watchlist_id", label: "Watchlist", type: "relation", relationTable: "watchlists", relationLabelKey: "name" },
      { key: "ticker", label: "Ticker", type: "text", required: true },
      { key: "name", label: "Name", type: "text" },
      { key: "market", label: "Market", type: "text" },
      { key: "note", label: "Note", type: "text" },
    ],
  },
  price_alerts: {
    table: "price_alerts",
    key: "price_alerts",
    label: "Alert",
    labelPlural: "Price Alerts",
    titleKey: "symbol",
    subtitleKeys: ["condition_type"],
    orderBy: { column: "created_at", ascending: false },
    fields: [
      { key: "symbol", label: "Symbol", type: "text", required: true },
      { key: "market", label: "Market", type: "text" },
      {
        key: "condition_type",
        label: "Condition",
        type: "select",
        options: [
          { value: "above", label: "Price above" },
          { value: "below", label: "Price below" },
        ],
        default: "above",
      },
      { key: "target_value", label: "Target value", type: "number", required: true },
      currency,
      { key: "is_active", label: "Active", type: "boolean", default: true },
      notes,
    ],
  },
  kpis: {
    table: "kpis",
    key: "kpis",
    label: "KPI",
    labelPlural: "KPIs",
    titleKey: "name",
    subtitleKeys: ["period"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "business_id", label: "Business", type: "relation", relationTable: "businesses", relationLabelKey: "name" },
      { key: "project_id", label: "Project", type: "relation", relationTable: "projects", relationLabelKey: "name" },
      { key: "target_value", label: "Target value", type: "number" },
      { key: "current_value", label: "Current value", type: "number" },
      { key: "unit", label: "Unit", type: "text" },
      { key: "period", label: "Period", type: "text" },
      { key: "frequency", label: "Frequency", type: "text" },
      notes,
    ],
  },
  kpi_entries: {
    table: "kpi_entries",
    key: "kpi_entries",
    label: "KPI Entry",
    labelPlural: "KPI Entries",
    titleKey: "value",
    orderBy: { column: "created_at", ascending: false },
    fields: [
      { key: "kpi_id", label: "KPI", type: "relation", relationTable: "kpis", relationLabelKey: "name", required: true },
      { key: "value", label: "Value", type: "number", required: true },
      { key: "period_start", label: "Period start", type: "date" },
      { key: "period_end", label: "Period end", type: "date" },
      notes,
    ],
  },
  reviews: {
    table: "reviews",
    key: "reviews",
    label: "Review",
    labelPlural: "Reviews",
    titleKey: "type",
    subtitleKeys: ["period_start"],
    orderBy: { column: "created_at", ascending: false },
    fields: [
      {
        key: "type",
        label: "Type",
        type: "select",
        required: true,
        options: [
          { value: "weekly", label: "Weekly" },
          { value: "monthly", label: "Monthly" },
        ],
        default: "weekly",
      },
      { key: "period_start", label: "Period start", type: "date", required: true },
      { key: "period_end", label: "Period end", type: "date", required: true },
      { key: "content", label: "Content", type: "textarea", required: true },
    ],
  },
  notes_table: {
    table: "notes",
    key: "notes_table",
    label: "Note",
    labelPlural: "Notes",
    titleKey: "title",
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    searchKeys: ["title", "content"],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "content", label: "Content", type: "textarea" },
      { key: "business_id", label: "Business", type: "relation", relationTable: "businesses", relationLabelKey: "name" },
      { key: "project_id", label: "Project", type: "relation", relationTable: "projects", relationLabelKey: "name" },
      { key: "goal_id", label: "Goal", type: "relation", relationTable: "goals", relationLabelKey: "title" },
      { key: "tags", label: "Tags", type: "tags" },
    ],
  },
  decisions: {
    table: "decisions",
    key: "decisions",
    label: "Decision",
    labelPlural: "Decisions",
    titleKey: "title",
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    searchKeys: ["title", "decision"],
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "context", label: "Context", type: "textarea" },
      { key: "decision", label: "Decision", type: "textarea", required: true },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "decided_on", label: "Decided on", type: "date" },
      { key: "business_id", label: "Business", type: "relation", relationTable: "businesses", relationLabelKey: "name" },
      { key: "project_id", label: "Project", type: "relation", relationTable: "projects", relationLabelKey: "name" },
      { key: "review_date", label: "Review date", type: "date" },
      { key: "outcome", label: "Outcome", type: "textarea" },
    ],
  },
  wishlist_categories: {
    table: "wishlist_categories",
    key: "wishlist_categories",
    label: "Category",
    labelPlural: "Wishlist Categories",
    titleKey: "name",
    orderBy: { column: "position", ascending: true },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "position", label: "Position", type: "number", default: 0 },
    ],
  },
  savings_goals: {
    table: "savings_goals",
    key: "savings_goals",
    label: "Savings goal",
    labelPlural: "Savings Goals",
    titleKey: "name",
    subtitleKeys: ["status"],
    orderBy: { column: "created_at", ascending: false },
    softDeleteColumn: "archived_at",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "target_amount", label: "Target amount", type: "money", required: true },
      currency,
      { key: "target_date", label: "Target date", type: "date" },
      priority3,
      status(["active", "paused", "done"], "active"),
      { key: "account_id", label: "Linked account", type: "relation", relationTable: "financial_accounts", relationLabelKey: "name" },
      notes,
    ],
  },
  wishlist_items: {
    table: "wishlist_items",
    key: "wishlist_items",
    label: "Wishlist item",
    labelPlural: "Wishlist",
    titleKey: "name",
    subtitleKeys: ["status"],
    orderBy: { column: "position", ascending: true },
    softDeleteColumn: "archived_at",
    searchKeys: ["name", "description", "merchant"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "category_id", label: "Category", type: "relation", relationTable: "wishlist_categories", relationLabelKey: "name" },
      { key: "savings_goal_id", label: "Savings goal", type: "relation", relationTable: "savings_goals", relationLabelKey: "name" },
      { key: "target_price", label: "Target price", type: "money" },
      { key: "current_estimated_price", label: "Current estimated price", type: "money" },
      currency,
      { key: "merchant", label: "Merchant", type: "text" },
      { key: "product_url", label: "Product URL", type: "text" },
      { key: "image_url", label: "Image URL", type: "text" },
      priority3,
      { key: "desired_date", label: "Desired by", type: "date" },
      status(["wanted", "saving", "ready", "purchased", "dropped"], "wanted"),
      { key: "description", label: "Description", type: "textarea" },
      notes,
    ],
  },
  savings_contributions: {
    table: "savings_contributions",
    key: "savings_contributions",
    label: "Contribution",
    labelPlural: "Contribution History",
    titleKey: "amount",
    subtitleKeys: ["entry_type"],
    orderBy: { column: "contributed_on", ascending: false },
    fields: [
      { key: "savings_goal_id", label: "Savings goal", type: "relation", relationTable: "savings_goals", relationLabelKey: "name", required: true },
      {
        key: "entry_type",
        label: "Type",
        type: "select",
        options: [
          { value: "contribution", label: "Contribution" },
          { value: "withdrawal", label: "Withdrawal" },
        ],
        default: "contribution",
      },
      { key: "amount", label: "Amount", type: "money", required: true },
      { key: "contributed_on", label: "Date", type: "date", required: true },
      { key: "account_id", label: "Account", type: "relation", relationTable: "financial_accounts", relationLabelKey: "name" },
      { key: "note", label: "Note", type: "text" },
    ],
  },
  wishlist_price_history: {
    table: "wishlist_price_history",
    key: "wishlist_price_history",
    label: "Price observation",
    labelPlural: "Price History",
    titleKey: "price",
    orderBy: { column: "observed_at", ascending: false },
    fields: [
      { key: "wishlist_item_id", label: "Wishlist item", type: "relation", relationTable: "wishlist_items", relationLabelKey: "name", required: true },
      { key: "price", label: "Price", type: "money", required: true },
      currency,
      { key: "observed_at", label: "Observed on", type: "date", required: true },
      { key: "source", label: "Source", type: "text" },
      { key: "merchant", label: "Merchant", type: "text" },
      notes,
    ],
  },
  top_priorities: {
    table: "top_priorities",
    key: "top_priorities",
    label: "Top priority",
    labelPlural: "Top Priorities",
    titleKey: "item_type",
    orderBy: { column: "position", ascending: true },
    fields: [
      { key: "priority_date", label: "Date", type: "date", required: true },
      {
        key: "item_type",
        label: "Item type",
        type: "select",
        required: true,
        options: [
          { value: "task", label: "Task" },
          { value: "project", label: "Project" },
        ],
      },
      { key: "item_id", label: "Item ID", type: "text", required: true },
      { key: "position", label: "Position", type: "number", default: 0 },
    ],
  },
};

export function getResource(key: string): ResourceDef {
  const r = RESOURCES[key];
  if (!r) throw new Error(`Unknown resource: ${key}`);
  return r;
}
