import type { ConstituentMeta } from "./types";

/**
 * SET50 constituents — Stock Exchange of Thailand's top 50 by market cap/liquidity.
 * Maintained as a static snapshot (index membership is rebalanced periodically by SET,
 * not something with a free live API). Prices/changes below are always fetched live from
 * Yahoo Finance — only this membership+name list is a periodically-refreshed snapshot.
 * Last reviewed: 2026-09.
 */
export const SET50: ConstituentMeta[] = [
  { symbol: "ADVANC", name: "Advanced Info Service", sector: "Communications" },
  { symbol: "AOT", name: "Airports of Thailand", sector: "Transportation" },
  { symbol: "AWC", name: "Asset World Corp", sector: "Property & Tourism" },
  { symbol: "BANPU", name: "Banpu", sector: "Energy" },
  { symbol: "BBL", name: "Bangkok Bank", sector: "Banking" },
  { symbol: "BDMS", name: "Bangkok Dusit Medical Services", sector: "Healthcare" },
  { symbol: "BEM", name: "Bangkok Expressway and Metro", sector: "Transportation" },
  { symbol: "BGRIM", name: "B.Grimm Power", sector: "Energy" },
  { symbol: "BH", name: "Bumrungrad Hospital", sector: "Healthcare" },
  { symbol: "BTS", name: "BTS Group Holdings", sector: "Transportation" },
  { symbol: "CBG", name: "Carabao Group", sector: "Food & Beverage" },
  { symbol: "CENTEL", name: "Central Plaza Hotel", sector: "Property & Tourism" },
  { symbol: "COM7", name: "Com7", sector: "Commerce" },
  { symbol: "CPALL", name: "CP All", sector: "Commerce" },
  { symbol: "CPF", name: "Charoen Pokphand Foods", sector: "Food & Beverage" },
  { symbol: "CPN", name: "Central Pattana", sector: "Property & Tourism" },
  { symbol: "CRC", name: "Central Retail Corporation", sector: "Commerce" },
  { symbol: "DELTA", name: "Delta Electronics (Thailand)", sector: "Electronics" },
  { symbol: "EA", name: "Energy Absolute", sector: "Energy" },
  { symbol: "EGCO", name: "Electricity Generating", sector: "Energy" },
  { symbol: "GLOBAL", name: "Siam Global House", sector: "Commerce" },
  { symbol: "GPSC", name: "Global Power Synergy", sector: "Energy" },
  { symbol: "GULF", name: "Gulf Energy Development", sector: "Energy" },
  { symbol: "HMPRO", name: "Home Product Center", sector: "Commerce" },
  { symbol: "INTUCH", name: "Intouch Holdings", sector: "Communications" },
  { symbol: "IVL", name: "Indorama Ventures", sector: "Petrochemicals" },
  { symbol: "KBANK", name: "Kasikornbank", sector: "Banking" },
  { symbol: "KTB", name: "Krung Thai Bank", sector: "Banking" },
  { symbol: "KTC", name: "Krungthai Card", sector: "Finance" },
  { symbol: "LH", name: "Land and Houses", sector: "Property & Tourism" },
  { symbol: "MINT", name: "Minor International", sector: "Food & Beverage" },
  { symbol: "MTC", name: "Muangthai Capital", sector: "Finance" },
  { symbol: "OR", name: "PTT Oil and Retail Business", sector: "Energy" },
  { symbol: "OSP", name: "Osotspa", sector: "Food & Beverage" },
  { symbol: "PTT", name: "PTT", sector: "Energy" },
  { symbol: "PTTEP", name: "PTT Exploration and Production", sector: "Energy" },
  { symbol: "PTTGC", name: "PTT Global Chemical", sector: "Petrochemicals" },
  { symbol: "RATCH", name: "Ratch Group", sector: "Energy" },
  { symbol: "SAWAD", name: "Srisawad Corporation", sector: "Finance" },
  { symbol: "SCB", name: "SCB X", sector: "Banking" },
  { symbol: "SCC", name: "Siam Cement", sector: "Construction Materials" },
  { symbol: "SCGP", name: "SCG Packaging", sector: "Packaging" },
  { symbol: "TIDLOR", name: "Ngern Tid Lor", sector: "Finance" },
  { symbol: "TISCO", name: "Tisco Financial Group", sector: "Banking" },
  { symbol: "TOP", name: "Thai Oil", sector: "Energy" },
  { symbol: "TRUE", name: "True Corporation", sector: "Communications" },
  { symbol: "TTB", name: "TMBThanachart Bank", sector: "Banking" },
  { symbol: "TU", name: "Thai Union Group", sector: "Food & Beverage" },
  { symbol: "WHA", name: "WHA Corporation", sector: "Property & Tourism" },
  { symbol: "VGI", name: "VGI", sector: "Communications" },
];
