import type { ConstituentMeta } from "./types";

/**
 * S&P 500 constituents — a curated set of the most liquid, widely-held large-cap names
 * across sectors, not a full 500-row enumeration (index membership is rebalanced by S&P
 * periodically and there's no free live API for the full list; a full 500-row table also
 * isn't practically useful on a mobile screen — this focuses the default/"View All" table
 * on names people actually look up). Prices/changes are always fetched live from Yahoo
 * Finance — only this membership+name list is a periodically-refreshed snapshot.
 * Last reviewed: 2026-09.
 */
export const SP500: ConstituentMeta[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", sector: "Communication Services" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)", sector: "Communication Services" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Communication Services" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { symbol: "BRK-B", name: "Berkshire Hathaway Inc.", sector: "Financials" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials" },
  { symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare" },
  { symbol: "V", name: "Visa Inc.", sector: "Financials" },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Energy" },
  { symbol: "MA", name: "Mastercard Incorporated", sector: "Financials" },
  { symbol: "COST", name: "Costco Wholesale Corporation", sector: "Consumer Staples" },
  { symbol: "HD", name: "The Home Depot Inc.", sector: "Consumer Discretionary" },
  { symbol: "PG", name: "The Procter & Gamble Company", sector: "Consumer Staples" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { symbol: "BAC", name: "Bank of America Corporation", sector: "Financials" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Technology" },
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
  { symbol: "KO", name: "The Coca-Cola Company", sector: "Consumer Staples" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", sector: "Technology" },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { symbol: "MCD", name: "McDonald's Corporation", sector: "Consumer Discretionary" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "Technology" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { symbol: "ACN", name: "Accenture plc", sector: "Technology" },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary" },
  { symbol: "DIS", name: "The Walt Disney Company", sector: "Communication Services" },
  { symbol: "LIN", name: "Linde plc", sector: "Materials" },
  { symbol: "TXN", name: "Texas Instruments Incorporated", sector: "Technology" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { symbol: "WFC", name: "Wells Fargo & Company", sector: "Financials" },
  { symbol: "INTC", name: "Intel Corporation", sector: "Technology" },
  { symbol: "VZ", name: "Verizon Communications Inc.", sector: "Communication Services" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
  { symbol: "IBM", name: "International Business Machines", sector: "Technology" },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { symbol: "UBER", name: "Uber Technologies Inc.", sector: "Technology" },
  { symbol: "QCOM", name: "QUALCOMM Incorporated", sector: "Technology" },
  { symbol: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { symbol: "SPGI", name: "S&P Global Inc.", sector: "Financials" },
  { symbol: "HON", name: "Honeywell International Inc.", sector: "Industrials" },
  { symbol: "BA", name: "The Boeing Company", sector: "Industrials" },
  { symbol: "UNP", name: "Union Pacific Corporation", sector: "Industrials" },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", sector: "Financials" },
  { symbol: "AXP", name: "American Express Company", sector: "Financials" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "RTX", name: "RTX Corporation", sector: "Industrials" },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { symbol: "SBUX", name: "Starbucks Corporation", sector: "Consumer Discretionary" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", sector: "Consumer Discretionary" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", sector: "Consumer Discretionary" },
  { symbol: "ELV", name: "Elevance Health Inc.", sector: "Healthcare" },
  { symbol: "MDT", name: "Medtronic plc", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare" },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financials" },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", sector: "Technology" },
  { symbol: "MU", name: "Micron Technology Inc.", sector: "Technology" },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Industrials" },
  { symbol: "DE", name: "Deere & Company", sector: "Industrials" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare" },
  { symbol: "MDLZ", name: "Mondelez International Inc.", sector: "Consumer Staples" },
  { symbol: "SCHW", name: "The Charles Schwab Corporation", sector: "Financials" },
  { symbol: "TJX", name: "The TJX Companies Inc.", sector: "Consumer Discretionary" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Healthcare" },
  { symbol: "CB", name: "Chubb Limited", sector: "Financials" },
  { symbol: "PGR", name: "The Progressive Corporation", sector: "Financials" },
  { symbol: "C", name: "Citigroup Inc.", sector: "Financials" },
  { symbol: "ETN", name: "Eaton Corporation plc", sector: "Industrials" },
  { symbol: "LMT", name: "Lockheed Martin Corporation", sector: "Industrials" },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", sector: "Technology" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { symbol: "SO", name: "The Southern Company", sector: "Utilities" },
  { symbol: "NEE", name: "NextEra Energy Inc.", sector: "Utilities" },
  { symbol: "CMG", name: "Chipotle Mexican Grill Inc.", sector: "Consumer Discretionary" },
  { symbol: "ANET", name: "Arista Networks Inc.", sector: "Technology" },
  { symbol: "SHOP", name: "Shopify Inc.", sector: "Technology" },
  { symbol: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { symbol: "AMAT", name: "Applied Materials Inc.", sector: "Technology" },
  { symbol: "BSX", name: "Boston Scientific Corporation", sector: "Healthcare" },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Technology" },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
  { symbol: "COIN", name: "Coinbase Global Inc.", sector: "Financials" },
  { symbol: "MMC", name: "Marsh & McLennan Companies", sector: "Financials" },
  { symbol: "CI", name: "The Cigna Group", sector: "Healthcare" },
  { symbol: "ADI", name: "Analog Devices Inc.", sector: "Technology" },
];
